#!/bin/sh
# Deployment script using DX CLI to push selected metadata files to any ORG Sanbox
# Input parameter specify target org alias for DX testdeploy, testdeploy etc

echo "--- START DEPLOYMENT FOR: testdeploy"

# Push Fields the -m option will deploy all Case object
#sfdx force:source:deploy -m CustomField:Case.Instance_URL__c -u testdeploy --wait 10
# For single field update use direct file path -p
sfdx force:source:deploy -p force-app/main/default/objects/Case/fields/CS_Reason__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Case/fields/CS_Activity__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Case/fields/TRL_Type__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Case/fields/TRL_Request_Type__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Case/fields/TRL_Task_Is_Clear__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Case/fields/TRL_Calc_Prio_Score__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Case/fields/Request_for_Assistance_by__c.field-meta.xml -u testdeploy --wait 10

# Case Record Type
sfdx force:source:deploy -p force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml -u testdeploy --wait 10

# Business process - Support process
sfdx force:source:deploy -p "force-app/main/default/objects/Case/businessProcesses/CS Tech Request.businessProcess-meta.xml" -u testdeploy --wait 10

sfdx force:source:deploy -p force-app/main/default/objects/Time_tracking__c/fields/CS_Reason__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Time_tracking__c/fields/CS_Activity__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Time_tracking__c/fields/Activity_Date__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Time_tracking__c/fields/Delivery_Resource__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Time_tracking__c/fields/Account_Name__c.field-meta.xml -u testdeploy --wait 10
sfdx force:source:deploy -p force-app/main/default/objects/Time_tracking__c/fields/AccountID__c.field-meta.xml -u testdeploy --wait 10


# Push LAyout change
sfdx force:source:deploy -m "Layout:Case-TRL" -u testdeploy --wait 10
sfdx force:source:deploy -m "Layout:Time_tracking__c-Time tracking Layout" -u testdeploy --wait 10

# Push Platform Event
sfdx force:source:deploy -m CustomObject:TRL_Case_Priorization_Event__e -u testdeploy --wait 10

# Push Classes
sfdx force:source:deploy -m ApexClass:TRL_Submit_CasePlatformEvent -u testdeploy --wait 10
sfdx force:source:deploy -m ApexClass:TRL_Submit_CasePlatformEventTest -u testdeploy --wait 10
sfdx force:source:deploy -m ApexClass:TRL_Action_New_CTRL -u testdeploy --wait 10
sfdx force:source:deploy -m ApexClass:TRL_Action_New_CTRLTest -u testdeploy --wait 10
sfdx force:source:deploy -m ApexClass:TRL_TimeTracking_ExtCtrl -u testdeploy --wait 10
sfdx force:source:deploy -m ApexClass:TRL_TimeTracking_ExtCtrlTest -u testdeploy --wait 10
# W-8372735 W-8372927
sfdx force:source:deploy -m ApexClass:TRL_Cases_only -u testdeploy --wait 10

# Push Pages
sfdx force:source:deploy -m ApexPage:TRL_TimeLog_New -u testdeploy --wait 10
sfdx force:source:deploy -m ApexPage:TRLCase_detail_page -u testdeploy --wait 10
sfdx force:source:deploy -m ApexPage:TRL_Action_New -u testdeploy --wait 10
sfdx force:source:deploy -m ApexPage:TRL_Action_Edit -u testdeploy --wait 10
sfdx force:source:deploy -m ApexPage:TRL_WithdrawnComment -u testdeploy --wait 10
# W-8372735 W-8372927
sfdx force:source:deploy -m ApexPage:TRLCases -u csdev --wait 10

# Push Permission Set fro DEV ONLY
##sfdx force:source:deploy -m PermissionSet:TRL_Permissions -u testdeploy --wait 10

echo "--- END DEPLOYMENT FOR: testdeploy"