#!/bin/sh
# Deployment script using DX CLI to push selected metadata files to any ORG Sanbox
# Input parameter specify target org alias for DX testdeploy, csdev etc

echo "--- START DEPLOYMENT FOR: csdev"

# Apex classes
sfdx force:source:deploy -m ApexClass:TRL_Cases_only -u csdev --wait 10

# sfdx force:source:retrieve -m ApexPage:TRL_TimeLog_New -u csdev --wait 10

# Push Templates
sfdx force:source:deploy -m EmailTemplate:TRL/Assignment_rule -u csdev --wait 10
sfdx force:source:deploy -m EmailTemplate:TRL/Notification_to_CSA_CSE -u csdev --wait 10
sfdx force:source:deploy -m EmailTemplate:TRL/TRL_case_status_is_work_in_progress -u csdev --wait 10

# Has error deploy fail:This Template Unique Name already exists or has been previously used.
#
#


echo "--- END DEPLOYMENT FOR: csdev"